#include "cxtestUtilities.h"
#include "cxtest_org_custusx_registration_method_manual_export.h"

namespace
{
EXPORT_DUMMY_CLASS_FOR_LINKING_ON_WINDOWS_IN_LIB_WITHOUT_EXPORTED_CLASS(CXTEST_ORG_CUSTUSX_REGISTRATION_METHOD_MANUAL_EXPORT)
}
