#ifndef SSCDEFINITIONSTRINGS_H_
#define SSCDEFINITIONSTRINGS_H_

#include "sscDefinitions.h"
#include "sscEnumConverter.h"

// put compiler-intensive templates here instead of in the much used sscDefinitions.h

namespace ssc
{
} //namespace end

SNW_DECLARE_ENUM_STRING_CONVERTERS(ssc, ORIENTATION_TYPE);
SNW_DECLARE_ENUM_STRING_CONVERTERS(ssc, PLANE_TYPE);
SNW_DECLARE_ENUM_STRING_CONVERTERS(ssc, FOLLOW_TYPE);
SNW_DECLARE_ENUM_STRING_CONVERTERS(ssc, CLINICAL_APPLICATION);
SNW_DECLARE_ENUM_STRING_CONVERTERS(ssc, MESSAGE_LEVEL);
SNW_DECLARE_ENUM_STRING_CONVERTERS(ssc, COORDINATE_SYSTEM);
SNW_DECLARE_ENUM_STRING_CONVERTERS(ssc, TRACKING_SYSTEM);
//SNW_DECLARE_ENUM_STRING_CONVERTERS(ssc, TOOL_TYPE);

#endif /*SSCDEFINITIONSTRINGS_H_*/
