# CustusX GitLab CI/CD configuration file

default:
  image: gitlab.sintef.no:5050/custusx/custusx/custusx-build-ubuntu2004:26.04.02

stages:
  - build-libs
  - build
  - test
  - deploy

variables:
  IMAGE_UBUNTU2004: "gitlab.sintef.no:5050/custusx/custusx/custusx-build-ubuntu2004:26.04.02"
  IMAGE_UBUNTU2204: "gitlab.sintef.no:5050/custusx/custusx/custusx-build-ubuntu2204:26.04.02"
  IMAGE_UBUNTU2404: "gitlab.sintef.no:5050/custusx/custusx/custusx-build-ubuntu2404:26.04.02"

include:
  - local: '.gitlab/ci/external-libs.yml'
  - local: '.gitlab/ci/build.yml'
  - local: '.gitlab/ci/test.yml'
  - local: '.gitlab/ci/deploy.yml'
