#ifndef CXDEFINITIONSTRINGS_H_
#define CXDEFINITIONSTRINGS_H_

#include "cxDefinitions.h"
#include "cxEnumConverter.h"

// put compiler-intensive templates here instead of in the much used sscDefinitions.h

namespace cx
{
} //namespace end

SNW_DECLARE_ENUM_STRING_CONVERTERS(cx, ORIENTATION_TYPE);
SNW_DECLARE_ENUM_STRING_CONVERTERS(cx, PLANE_TYPE);
SNW_DECLARE_ENUM_STRING_CONVERTERS(cx, FOLLOW_TYPE);
SNW_DECLARE_ENUM_STRING_CONVERTERS(cx, CLINICAL_APPLICATION);
SNW_DECLARE_ENUM_STRING_CONVERTERS(cx, MESSAGE_LEVEL);
SNW_DECLARE_ENUM_STRING_CONVERTERS(cx, COORDINATE_SYSTEM);
SNW_DECLARE_ENUM_STRING_CONVERTERS(cx, TRACKING_SYSTEM);
//SNW_DECLARE_ENUM_STRING_CONVERTERS(ssc, TOOL_TYPE);

#endif /*CXDEFINITIONSTRINGS_H_*/
