// This file is part of CustusX, an Image Guided Therapy Application.
//
// Copyright (C) 2008- SINTEF Technology & Society, Medical Technology
//
// CustusX is fully owned by SINTEF Medical Technology (SMT). CustusX source
// code and binaries can only be used by SMT and those with explicit permission
// from SMT. CustusX shall not be distributed to anyone else.
//
// CustusX is a research tool. It is NOT intended for use or certified for use
// in a normal clinical setting. SMT does not take responsibility for its use
// in any way.
//
// See CustusX_License.txt for more information.

#ifndef CXLAYOUTWIDGET_H
#define CXLAYOUTWIDGET_H

#include "sscView.h"
#include "cxLayoutData.h"
class QGridLayout;

namespace cx
{

/** A widget containing all the views generated by ViewManager,
 *  described by a LayoutData.
 *
 * \ingroup cxServiceVisualization
 * \date 05.11.2013
 * \author christiana
 */
class LayoutWidget : public QWidget
{
	Q_OBJECT
public:
	LayoutWidget();
	~LayoutWidget();
	/** Set the stretch factors of columns and rows in mLayout.
	 */
	void setStretchFactors(LayoutRegion region, int stretchFactor);
	void addView(ViewWidget* view, LayoutRegion region);
	void clearViews();
	void setLayoutName(QString name);
	QString getLayoutName() const;

private:
	QString mLayoutName;
	QGridLayout* mLayout; ///< the layout
	std::vector<ViewWidget*> mViews;
};


} // namespace cx

#endif // CXLAYOUTWIDGET_H
