set(Require-Plugin org.custusx.registration)
set(Plugin-Name "Registration GUI")
set(Plugin-Version "0.1.0")
set(Plugin-Vendor "SINTEF")
set(Plugin-Category "Registration GUI")
#set(Plugin-ContactAddress "")
